fixing up redirection of an echo cmd

diff --git a/vm/tools/nd_createappliance b/vm/tools/nd_createappliance
--- a/vm/tools/nd_createappliance
+++ b/vm/tools/nd_createappliance
@@ -66,7 +66,7 @@ clean_buildvm                   # clean things up
 # Check that no previous VM was left (can happen if previous failures
 # were "valid")
 if VBoxManage list vms | grep -q "^\"${vm_name}\".*"; then
-    echo >&2, "VM $vm_name still exists -- something is wrong, Can't continue"
+    echo "VM $vm_name still exists -- something is wrong, Can't continue" >&2
     exit 1
 fi
 
