fix up using of NEURODEBIAN_UPDATE + updated changelog

diff --git a/tools/nd-configurerepo b/tools/nd-configurerepo
--- a/tools/nd-configurerepo
+++ b/tools/nd-configurerepo
@@ -397,7 +397,7 @@ while true ; do
       -n|--dry-run)        ae_dry_run=1; shift;;
          --suffix) shift;  ae_suffix="$1"; shift;;
          --overwrite)      ae_overwrite="$1"; shift;;
-         --do-not-update)  ae_update=""; shift;;
+         --do-not-update)  ae_update=0; shift;;
          --sources)        ae_sources=1; shift;;
          --no-sources)     ae_sources=0; shift;;
          --install)        ae_install=1; shift;;
@@ -473,7 +473,7 @@ fi
 case $ae_flavor in
  full)  apt_flavor="contrib non-free";;
  libre) apt_flavor="";;
- *) error 5 "Unknown value of flavor $apt_flavor.  Must be full or libre"
+ *) error 7 "Unknown value of flavor $apt_flavor.  Must be full or libre"
 esac
 
 if [ -z "$ae_sources" ]; then
@@ -555,7 +555,7 @@ fi
 # Finalizing (apt-get update etc)
 #
 
-if [ ! -z "$ae_update" ]; then
+if [ "$ae_update" = "1" ]; then
     print_verbose 1 "Updating APT listings, might take a few minutes"
     if [ -z "$ae_dry_run" ]; then
         apt_logfile="$ae_tempdir/apt.log"
@@ -563,12 +563,14 @@ if [ ! -z "$ae_update" ]; then
             && rm -f "$apt_logfile" \
             || {
                  apt_log=$(cat "$apt_logfile")
-                 echo "$apt_log"
+                 print_verbose 0 "$apt_log"
                  if echo "$apt_log" | grep -q "Malformed line [0-9]* in source list $ae_output_file"; then
                      $ae_sudo mv "${ae_output_file}" "${ae_output_file}-failed.disabled"
                      error 6 "Update failed to possible errorneous APT listing file produced by this script.  Generated $ae_output_file renamed to ${ae_output_file}-failed.disabled to not interfer"
                  fi
-                 error 5 "Update failed with exit code $? (above output logged into $apt_logfile)."
+                 # TODO: too late for $? -- need to store right after apt-get update run
+                 #       log file would get removed, so not worth bringin it up
+                 error 5 "Update failed with exit code $?."
                  }
     else
         eval_dry apt-get update
