do not fail nd_updatedist if one arch failed to update
i386 is gone in some, we have no flexibility atm on per release/arch specification

diff --git a/tools/nd_updatedist b/tools/nd_updatedist
--- a/tools/nd_updatedist
+++ b/tools/nd_updatedist
@@ -33,5 +33,5 @@ fi
 
 for a in $arch; do
   echo "Updating arch $a..."
-  cowbuilder --update --basepath ${cowbuilderroot}/cow/${family}-${dist}-${a}.cow $opts
+  cowbuilder --update --basepath ${cowbuilderroot}/cow/${family}-${dist}-${a}.cow $opts || echo "failed to update for $arch"
 done
